name: 'Terraform Azure Storage Deployment'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.f858b38e-80b7-4310-ab3e-946e7beef94c }}
  ARM_CLIENT_SECRET: ${{ secrets.4J38Q~FFU3kBh1VZJ5vIO1VMKtQoREWHaGpGjaao }}
  ARM_TENANT_ID: ${{ secrets.9db38ab7-eaaf-426c-be69-0e8473755dd3 }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.fdddaca3-a991-4301-8149-389bb3aaf4f9 }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
